.TH xrandr-align 1

.SH NAME
xrandr-align - utility to align an X input device in accordance with
the screen rotation

.SH SYNOPSIS
.B xrandr-align [OPTIONS] [FUNCTION] [FUNCTION-OPTIONS]

.SH DESCRIPTION
xrandr-align is a utility to align an X input device in accordance
with the screen rotation, panning and scale parameters controlled by
the X RandR extension. In addition the utility can list available
input devices and screen outputs.

.SH OPTIONS
.TP 8
.B -v | --verbose
Turns on the verbose output mode.

.SH FUNCTIONS
.TP 8
.B version
Prints out the program version and the versions of XInput and XRandR
extensions available on the running X server. This function does not
require any additional options.
.PP
.TP 8
.B list-input [--short | --long] [\fIdevice\fP]
If no argument is given list all available input devices. If an
argument is given, show all the features of the given \fIdevice\fP.
If --long is provided, the output includes detailed information about
the capabilities of each devices. Otherwise, or if --short is
provided, only the device names and some minimal information is
listed.
.PP
.TP 8
.B list-output [--screen=\fInumber\fP]
If no argument is given list all available screen outputs. Optionally
the screen \fnumber\fP can be specified.
.PP
.TP 8
.B align [--input=\fIdevice\fP] [--screen=\fInumber\fP] [--output=\fIoutput\fP]
The default function. It is called when no function name is given. It
queries the current screen configuration and applies the current
coordinate transformation to the input device. If no options are given
then the Core Pointer and the Primary Output (or the first available
output) is used in correspondence. The name or the ID of the input
device can be specified with the \fIinput\fP. The name or ID of the
output can explicitly specified with the \fIoutput\fP option. For
multiple screen configuration the output selection can be narrowed by
specifying the screen \fInumber\fP.
.PP
.TP 8
.B monitor [--input=\fIdevice\fP] [--screen=\fInumber\fP] [--output=\fIoutput\fP]
Listens for screen (CRTC, output) change events from RandR end applies
each coordinate transformation to the input device. If no options are
given then the Core Pointer and the Primary Output (or the first
available output) is used in correspondence. The name or the ID of the
input device can be specified with the \fIinput\fP. The name or ID of
the output can explicitly specified with the \fIoutput\fP option. For
multiple screen configuration the output selection can be narrowed by
specifying the screen \fInumber\fP.

.SH ENVIRONMENT
The program uses the \fBDISPLAY\fP environment variable specifying the
X display to connect.

.SH "SEE ALSO"
xinput(1), xrandr(1)

.SH LICENSE
Permission to use, copy, modify, distribute, and sell this software
and its documentation for any purpose is  hereby granted without fee,
provided that the  above copyright   notice appear  in   all  copies
and  that both  that copyright  notice   and   this  permission
notice  appear  in  supporting documentation, and that   the  name of
the authors  not  be  used  in advertising or publicity pertaining to
distribution of the software without specific,  written prior
permission. The authors  make  no representations about the
suitability of this software for any purpose.  It is provided "as is"
without express or implied warranty.

THE AUTHORS DISCLAIM ALL   WARRANTIES WITH REGARD  TO  THIS SOFTWARE,
INCLUDING ALL IMPLIED   WARRANTIES OF MERCHANTABILITY  AND   FITNESS,
IN NO EVENT  SHALL THE AUTHORS  BE   LIABLE   FOR ANY  SPECIAL,
INDIRECT   OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
RESULTING FROM LOSS OF USE, DATA  OR PROFITS, WHETHER  IN  AN ACTION
OF  CONTRACT,  NEGLIGENCE OR OTHER TORTIOUS  ACTION, ARISING    OUT OF
OR   IN  CONNECTION  WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

.SH COPYRIGHT
Copyright 2012, Paul Wolneykien, ALT Linux Ltd.
.PP
Original \fBxinput\fP utility:
.nf
Copyright 1996,1997, Frederic Lepied.
Copyright 2008, Philip Langdale.
.PP
Original \fBxrandr\fP utility:
.nf
Copyright 2001 Keith Packard.

.SH AUTHORS

.nf
Paul Wolneykien <manowar@altlinux.org>
Philip Langdale, <philipl@alumni.utexas.net>
Frederic Lepied, France <Frederic.Lepied@sugix.frmug.org>
Peter Hutterer <peter.hutterer@who-t.net>
Julien Cristau <jcristau@debian.org>
Thomas Jaeger <ThJaeger@gmail.com>
Keith Packard, Open Source Technology Center, Intel Corporation
Jim Gettys, Cambridge Research Laboratory, HP Labs, HP
and more.
.fi
